"teacher can login and logout; also introduces Rspec testing"
create authentications controller, form_for login, but does not access teacher data in ActiveRecord

infinte loop throwing SystemStackError: stack level too deep at params in authentication_controller

commit with undefined method 'password_digest' error

migrate add_password_digest_to_teachers which also removes password and password_confirmation columns

first pass at TDD with Rspec, wanted something on github

correct params in authentications_controller to stop loop

no method error 'limit' in teachers_controller

remove validation(:password, :uniqueness :true)

remove tests copied from todo app